name: Backend CD

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: my-app
  REGION: europe-west1

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set ARTIFACT_REPO
        run: echo "ARTIFACT_REPO=${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests
        working-directory: backend
        run: PYTHONPATH=. pytest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Ensure Artifact Registry exists
        run: |
          REPO_NAME=my-docker-repo
          REGION=${{ env.REGION }}
          PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          EXISTS=$(gcloud artifacts repositories list --location=$REGION --project=$PROJECT_ID --format="value(name)" | grep $REPO_NAME || true)
          if [ -z "$EXISTS" ]; then
            echo "Repository $REPO_NAME not found, creating..."
            gcloud artifacts repositories create $REPO_NAME \
              --repository-format=docker \
              --location=$REGION \
              --description="Docker repo for ${{ env.SERVICE_NAME }}"
          else
            echo "Repository $REPO_NAME already exists."
          fi

      - name: Build Docker image
        run: docker build -t ${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${GITHUB_SHA} ./backend

      - name: Push Docker image
        run: docker push ${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${GITHUB_SHA}

      - name: Deploy Backend
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${GITHUB_SHA} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }},DATABASE_DIRECT=${{ secrets.DATABASE_DIRECT }}

      - name: Ensure public access to backend
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --member="allUsers" \
            --role="roles/run.invoker"


      - name: Get Backend URL
        id: get-backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)')
          echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_ENV
          echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT

      - name: Install Vercel CLI
        run: npm install -g vercel@46.1.0

      - name: Deploy Frontend with updated BACKEND_URL
        run: |
          set -e

          echo "Removing old VITE_API_URL..."
          vercel env rm VITE_API_URL production --yes --token $VERCEL_TOKEN || true

          echo "Adding updated VITE_API_URL..."
          echo "$BACKEND_URL" | vercel env add VITE_API_URL production --token $VERCEL_TOKEN

          echo "Deploying frontend..."
          FRONTEND_URL=$(vercel --prod --token $VERCEL_TOKEN --confirm --yes | grep "https://" | head -n1)
          echo "FRONTEND_URL=$FRONTEND_URL" >> $GITHUB_ENV
        env:
          BACKEND_URL: ${{ steps.get-backend-url.outputs.url }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Update Backend CORS dynamically
        run: |
          echo "Redeploy backend with FRONTEND_URL for CORS..."
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${GITHUB_SHA} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars FRONTEND_URL=$FRONTEND_URL
        env:
          FRONTEND_URL: ${{ env.FRONTEND_URL }}
