name: Backend CD

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: my-app

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests
        working-directory: backend
        run: PYTHONPATH=. pytest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker auth
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA ./backend

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA

      - name: Deploy Backend
        run: |
          gcloud run deploy my-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated

      - name: Get Backend URL
        id: get-backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe my-app --region europe-west1 --format 'value(status.url)')
          echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_ENV
          echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT

      - name: Install Vercel CLI
        run: npm install -g vercel@46.1.0

      - name: Deploy Frontend with updated BACKEND_URL
        run: |
          set -e

          # Remove old environment variable on frontend
          echo "Removing old VITE_API_URL..."
          vercel env rm VITE_API_URL production --yes --token $VERCEL_TOKEN || true

          # Add updated backend URL as VITE_API_URL
          echo "Adding updated VITE_API_URL..."
          echo "$BACKEND_URL" | vercel env add VITE_API_URL production --token $VERCEL_TOKEN

          # Deploy frontend
          echo "Deploying frontend..."
          FRONTEND_URL=$(vercel --prod --token $VERCEL_TOKEN --confirm --yes | grep "https://" | head -n1)
          echo "FRONTEND_URL=$FRONTEND_URL" >> $GITHUB_ENV

        env:
          BACKEND_URL: ${{ steps.get-backend-url.outputs.url }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Update Backend CORS dynamically
        run: |
          echo "Redeploy backend with FRONTEND_URL for CORS..."
          gcloud run deploy my-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars FRONTEND_URL=$FRONTEND_URL
        env:
          FRONTEND_URL: ${{ env.FRONTEND_URL }}
