name: Grindly

on:
    push:
        branches:
            - main
            - feature/*
            - refactor/*
    pull_request:
        branches: 
            - main
            - feature/*
            - refactor/*
            - develop

jobs:
    test-and-run:
        runs-on: ubuntu-latest

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Build Docker image
              run: |
                docker build -t grindly-backend ./backend

            - name: Run tests and app in one container
              run: |
                # Run container in the background
                docker run --rm \
                --env DATABASE_URL=$DATABASE_URL \
                --env HOST=0.0.0.0 \
                grindly-backend \
                bash -c "uvicorn app.main.app --host $HOST --port 8000 & \
                python -m pytest -s app/tests && \
                curl -f http://localhost:8000/docs"

