name: Grindly

on:
    push:
        branches:
            - main
            - feature/*
            - refactor/*
    pull_request:
        branches: 
            - main
            - feature/*
            - refactor/*
            - develop

jobs:
    test-and-run:
        runs-on: ubuntu-latest

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Build Docker image
              run: |
                docker build -t grindly-backend ./backend

            - name: Run tests and app in one container
              run: |
                # Run container in the background
                docker run -d --name grindly-backend-test --env DATABASE_URL=$DATABASE_URL grindly-backend

                # Run tests inside the container
                docker exec grindly-backend-test python -m pytest -s app/tests

                # Check the base endpoint of the app
                sleep 5
                docker exec grindly-backend-test curl http://localhost:8000/docs

                # Stop and remove container
                docker stop grindly-backend-test
                docker rm grindly-backend-test

